-- =====================================================================
-- MIGRAÇÃO DE RECRIAÇÃO DA TABELA QUESTOES (PADRÃO CANÔNICO JSON 1:1)
-- =====================================================================
-- Execute este script no SQL Editor do seu Dashboard no Supabase.

DROP TABLE IF EXISTS public.questoes CASCADE;

CREATE TABLE public.questoes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_qc              TEXT NOT NULL UNIQUE,
  disciplina         TEXT NOT NULL DEFAULT 'Geral',
  banca              TEXT,
  ano                INTEGER CHECK (ano IS NULL OR (ano BETWEEN 1900 AND 2100)),
  orgao              TEXT,
  cargo              TEXT,
  assunto            TEXT,
  tipo               TEXT NOT NULL DEFAULT 'multipla_escolha' CHECK (tipo IN ('multipla_escolha', 'certo_errado')),
  enunciado          TEXT NOT NULL,
  alternativas       JSONB NOT NULL DEFAULT '[]'::jsonb,
  resposta_correta   TEXT,
  gabarito_comentado TEXT,
  imagem_url         TEXT,
  imagens            JSONB DEFAULT '[]'::jsonb,
  quality_metrics    JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_released        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices de Alta Performance para Filtragem Rápida
CREATE INDEX IF NOT EXISTS idx_questoes_id_qc ON public.questoes(id_qc);
CREATE INDEX IF NOT EXISTS idx_questoes_disciplina ON public.questoes(disciplina);
CREATE INDEX IF NOT EXISTS idx_questoes_banca ON public.questoes(banca);
CREATE INDEX IF NOT EXISTS idx_questoes_ano ON public.questoes(ano);
CREATE INDEX IF NOT EXISTS idx_questoes_assunto ON public.questoes(assunto);
CREATE INDEX IF NOT EXISTS idx_questoes_tipo ON public.questoes(tipo);
CREATE INDEX IF NOT EXISTS idx_questoes_is_released ON public.questoes(is_released);

-- Trigger de atualização de updated_at
CREATE TRIGGER questoes_updated_at
  BEFORE UPDATE ON public.questoes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Habilitar RLS (Row-Level Security)
ALTER TABLE public.questoes ENABLE ROW LEVEL SECURITY;

-- Política de Leitura Pública / Autenticada
CREATE POLICY "questoes_select_all"
  ON public.questoes FOR SELECT
  TO authenticated, anon
  USING ( true );

-- Política de Administração Total para Admins
CREATE POLICY "questoes_admin_all"
  ON public.questoes FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = (SELECT auth.uid()) AND role = 'admin'
    )
-- Recarregar o cache do PostgREST imediatamente
NOTIFY pgrst, 'reload schema';
