-- Catálogo de questões de concursos.
-- As alternativas ficam em JSONB para preservar questões com quatro ou mais opções.
create table public.questoes (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  disciplina text,
  tema text,
  ano integer,
  banca text,
  orgao text,
  prova text,
  enunciado text not null,
  alternativas jsonb not null default '[]'::jsonb,
  resposta_correta text,
  grau_dificuldade text,
  imagem_url text,
  explanation text,
  quality_metrics jsonb not null default '{}'::jsonb,
  is_released boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint questoes_ano_valido check (ano is null or ano between 1900 and 2100),
  constraint questoes_resposta_correta_valida check (
    resposta_correta is null or resposta_correta in ('A', 'B', 'C', 'D', 'E')
  ),
  constraint questoes_grau_dificuldade_valido check (
    grau_dificuldade is null
    or grau_dificuldade in ('Fácil', 'Médio', 'Difícil')
    or grau_dificuldade ~ '^\\d+(\\.\\d+)?$'
  ),
  constraint questoes_alternativas_array check (jsonb_typeof(alternativas) = 'array')
);

create schema if not exists private;

create or replace function private.gerar_codigo_questao()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.codigo := 'Q' || lpad(new.id::text, 7, '0');
  return new;
end;
$$;

create trigger questoes_gerar_codigo
  before insert on public.questoes
  for each row execute function private.gerar_codigo_questao();

create trigger questoes_updated_at
  before update on public.questoes
  for each row execute function public.set_updated_at();

-- Preserva as questões já cadastradas no modelo anterior.
insert into public.questoes (
  disciplina,
  tema,
  ano,
  banca,
  orgao,
  prova,
  enunciado,
  alternativas,
  resposta_correta,
  grau_dificuldade,
  imagem_url,
  explanation,
  quality_metrics,
  is_released,
  created_at,
  updated_at
)
select
  q.subject,
  q.topic,
  case
    when q.quality_metrics #>> '{source_metadata,year}' ~ '^\\d{4}$'
      then (q.quality_metrics #>> '{source_metadata,year}')::integer
    else null
  end,
  q.quality_metrics #>> '{source_metadata,exam_board}',
  q.quality_metrics #>> '{source_metadata,organization}',
  q.pdf_name,
  q.statement,
  coalesce(
    (
      select jsonb_agg(
        jsonb_build_object('letra', option_data.value ->> 'letter', 'texto', option_data.value ->> 'text')
        order by option_data.ordinality
      )
      from jsonb_array_elements(q.options) with ordinality as option_data(value, ordinality)
    ),
    '[]'::jsonb
  ),
  q.correct_option,
  q.quality_metrics ->> 'difficulty_level',
  q.quality_metrics #>> '{source_metadata,image_url}',
  q.explanation,
  q.quality_metrics,
  q.is_released,
  q.created_at,
  q.updated_at
from public.questions q;

alter table public.questoes enable row level security;

create policy "questoes_select_released"
  on public.questoes for select
  to authenticated
  using (is_released = true);

create policy "questoes_all_admin"
  on public.questoes for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where id = (select auth.uid()) and role = 'admin'
    )
  );

grant select on public.questoes to authenticated, service_role;
grant insert, update, delete on public.questoes to service_role;

create index questoes_released_created_at_idx
  on public.questoes (created_at desc)
  where is_released = true;

create index questoes_disciplina_tema_idx
  on public.questoes (disciplina, tema);
