-- ================================================================
-- Migration: user_question_answers
-- Persistencia de respostas de questoes por usuario
-- Execute no Supabase SQL Editor
-- ================================================================

-- Tabela principal
create table if not exists public.user_question_answers (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  question_id  text not null,
  disciplina   text not null default 'Geral',
  banca        text,
  ano          integer,
  is_correct   boolean not null,
  answered_at  timestamptz not null default now(),
  unique(user_id, question_id)
);

-- RLS
alter table public.user_question_answers enable row level security;

create policy "uqa_select_own"
  on public.user_question_answers for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "uqa_insert_own"
  on public.user_question_answers for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "uqa_update_own"
  on public.user_question_answers for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update on public.user_question_answers to authenticated, service_role;

-- Index para query de stats por disciplina
create index if not exists uqa_user_disciplina_idx
  on public.user_question_answers (user_id, disciplina);

create index if not exists uqa_user_answered_at_idx
  on public.user_question_answers (user_id, answered_at desc);

-- ================================================================
-- RPC: get_accuracy_by_disciplina
-- Retorna acerto percentual por disciplina para o usuario logado
-- ================================================================
create or replace function public.get_accuracy_by_disciplina()
returns table(
  disciplina  text,
  total       bigint,
  corretas    bigint,
  pct         numeric
)
language sql
security definer
set search_path = ''
as $$
  select
    a.disciplina,
    count(*)                                          as total,
    count(*) filter (where a.is_correct = true)      as corretas,
    round(
      count(*) filter (where a.is_correct = true)::numeric
      / nullif(count(*), 0) * 100
    , 1)                                             as pct
  from public.user_question_answers a
  where a.user_id = (select auth.uid())
  group by a.disciplina
  order by pct desc, total desc;
$$;

grant execute on function public.get_accuracy_by_disciplina() to authenticated;
